---
permalink: concept-report-management.html 
sidebar: sidebar 
keywords: view, delete, backup, restore, configuration, report, snapmanager, hyper-v, information, virtual, machine, vm, managing, manage 
summary: Vous pouvez afficher et supprimer les rapports de sauvegarde, de restauration et de configuration dans SnapManager for Hyper-V. Ces rapports contiennent des informations importantes sur vos jeux de données, vos machines virtuelles et vos hôtes. Vous pouvez également exporter des rapports dans différents formats. 
---
= Gérer les rapports
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Vous pouvez afficher et supprimer les rapports de sauvegarde, de restauration et de configuration dans SnapManager for Hyper-V. Ces rapports contiennent des informations importantes sur vos jeux de données, vos machines virtuelles et vos hôtes. Vous pouvez également exporter des rapports dans différents formats.

* *Rapports de sauvegarde*
+
Les rapports de sauvegarde affichent toutes les informations de sauvegarde pour tous les hôtes appartenant à un jeu de données particulier. Vous pouvez afficher un rapport de sauvegarde pour un jeu de données ou une machine virtuelle. Les rapports affichés pour une machine virtuelle utilisent le nom de la machine virtuelle au lieu de son GUID.

+
Lorsque le rapport de sauvegarde est affiché, vous pouvez l'exporter dans plusieurs formats différents.

* *Restaurer les rapports*
+
Les rapports de restauration affichent toutes les informations relatives à l'opération de restauration sur la base d'une machine virtuelle.

+
Lorsque le rapport de restauration est affiché, vous pouvez l'exporter dans plusieurs formats différents.

* *Rapports de configuration*
+
Les rapports de configuration affichent les paramètres de notification, le chemin du rapport et le chemin SnapInfo pour l'hôte sélectionné.

+
Lorsque le rapport de configuration est affiché, vous pouvez l'exporter dans plusieurs formats différents.


