---
permalink: reference-either-the-specified-vm-s-are-not-present-or-they-cannot-be-backed-up-online.html 
sidebar: sidebar 
keywords: vm, present, backed, up, online 
summary: La ou les VM spécifiés ne sont pas présentes ou ne peuvent pas être sauvegardées en ligne 
---
= La ou les VM spécifiés ne sont pas présentes ou ne peuvent pas être sauvegardées en ligne
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Message*
+
`Either the specified VM(s) are not present or they cannot be backed up online`

* *Description*
+
Ce message s'explique notamment par l'échec des sauvegardes cohérentes avec les applications si la taille du disque de transmission sur la machine virtuelle est inférieure à 300 Mo. Votre journal d'erreurs ressemblera à l'exemple suivant :

+
[listing]
----
Log Name:      Application
Source:        SnapMgrServiceHost
Date:          11/12/2012 12:24:28 PM
Event ID:      106
Task Category: Backup Event
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      defiant16.wak-qa.com
Description:
SnapManager for Hyper-V backup failed to complete

Backup Failed for the following VM(s) since it cannot be backedup online or No VM to be found for backup
               VM Name: demovm-0
----
+
Il n'y a pas d'autres messages d'erreur système ou d'application pour indiquer l'échec.

* * Action corrective*
+
Vous pouvez soit redimensionner le disque intermédiaire pour qu'il soit supérieur à 300 Mo, soit exécuter la sauvegarde avec l'option Autoriser la sauvegarde VM à l'état enregistré activée.

+

NOTE: Cette action corrective s'applique aussi bien aux environnements SAN que NAS.

* *Message*
+
`Either the specified VM(s) are not present or they cannot be backed up online`

* *Description*
+
La deuxième raison de ce message est que Windows ne peut pas effectuer de sauvegarde en ligne de ce système, car l'option snapshots évalués pour Hyper-V VM est activée. Les snapshots évalués sont principalement utilisés par les mises à jour critiques Windows.

* * Action corrective*
+
Vous devez désactiver le `scoped snapshots` En créant un DWORD `ScopeSnapshots` paramètre avec la valeur 0 dans :

+
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion\SystemRestore\`

+

NOTE: Cette action corrective s'applique aussi bien aux environnements SAN que NAS.


