---
permalink: reference-dataset-backup-might-fail-with-a-partial-writer-error.html 
sidebar: sidebar 
keywords: vss, requestor, backup, component, partial, writer, error 
summary: VSS Requestor - échec des composants de sauvegarde avec une erreur de graveur partiel. 
---
= VSS Requestor - échec des composants de sauvegarde avec une erreur de graveur partiel
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Message*
+
[listing]
----
Error: Vss Requestor - Backup Components failed with partial
writer error.
Writer Microsoft Hyper-V VSS Writer involved in backup or restore
operation reported partial failure. Writer returned failure code
0x80042336. Writer state is 5.
Application specific error information:
Application error code: 0x1
Application error message: -
Failed component information:
Failed component: VM GUID XXX
    Writer error code: 0x800423f3
    Application error code: 0x8004230f
    Application error message: Failed to revert to VSS snapshot on the
    virtual hard disk 'volume_guid' of the virtual machine 'vm_name'.
   (Virtual machine ID XXX)
----
+
Les erreurs suivantes apparaissent dans le journal des événements de l'application Windows sur l'hôte Hyper-V :

+
[listing]
----
Volume Shadow Copy Service error: Unexpected error calling routine
GetOverlappedResult.  hr = 0x80070057, The parameter is incorrect.

Operation:
   Revert a Shadow Copy

Context:
   Execution Context: System Provider

Volume Shadow Copy Service error: Error calling a routine on a Shadow
Copy Provider
{b5946137-7b9f-4925-af80-51abd60b20d5}. Routine details
RevertToSnapshot
[hr = 0x80042302, A Volume Shadow Copy Service component encountered
an unexpected
error.
Check the Application event log for more information.].

Operation:
   Revert a Shadow Copy

Context:
   Execution Context: Coordinator
----
* *Description*
+
Ce message s'affiche lorsque vous effectuez une sauvegarde cohérente avec les applications d'un jeu de données. Cette erreur entraîne l'échec de la sauvegarde pour certaines machines virtuelles du jeu de données.

* * Action corrective*
+
** Relancez la sauvegarde du jeu de données.
** Si la tentative de nouvelle tentative échoue, séparez le jeu de données en deux jeux de données afin de placer tous les VM dont la sauvegarde a échoué dans un jeu de données unique et toutes les autres VM dans un autre jeu de données. Puis exécutez à nouveau la sauvegarde.



