---
permalink: reference-vss-requestor-backup-components-failed-failed-to-call-keep-snapshot-set.html 
sidebar: sidebar 
keywords: vss, requestor, backup, component, fail, call, snapshot, set 
summary: 'VSS Requestor - échec des composants de sauvegarde. Impossible d"appeler conserver le snapshot défini.' 
---
= VSS Requestor - échec des composants de sauvegarde. Impossible d'appeler conserver le snapshot défini.
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Erreur*
+
`Vss Requestor - Backup Components failed. Failed to call keep snapshot set. Reason Index and count must refer to a location within the string.`

* *Description*
+
Cette erreur se produit lorsque les machines virtuelles d'une tâche de sauvegarde résident sur un Storage Virtual machine et un serveur CIFS portant le même nom.

* * Action corrective*
+
Aucune disponible pour cette version.

* *Exemple d'échec*
+
.. Créez un Storage Virtual machine et un serveur CIFS portant le même nom : par exemple « test1 ».
.. Ajoutez le nom tes1 au DNS avec les deux adresses IP.
.. Sur un hôte Windows Server 2012, installez SnapManager pour Hyper-V et créez quelques machines virtuelles en utilisant les partages CIFS du test 1.
.. Créer une copie de sauvegarde incluant ces machines virtuelles.
.. Notez que la procédure de sauvegarde échoue avec l'erreur : `Backup Components failed. Failed to call keep snapshot set. Reason Index and count must refer to a location within the string.`



