---
permalink: task-change-the-snapinfo-directory-path.html 
sidebar: sidebar 
keywords: control, snapinfo, directory, path, setting, configuration, wizard, action, changing, change 
summary: 'Vous pouvez contrôler les paramètres du chemin d"accès au répertoire SnapInfo à l"aide de l"assistant de configuration ou des paramètres SnapInfo.' 
---
= Modifiez le chemin d'accès au répertoire SnapInfo
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Vous pouvez contrôler les paramètres du chemin d'accès au répertoire SnapInfo à l'aide de l'assistant de configuration ou de l'action *SnapInfo*.

Les paramètres du répertoire SnapInfo sont spécifiés au niveau de l'hôte dans SnapManager pour Hyper-V. SnapManager pour Hyper-V prend en charge les hôtes NAS (SMB) et les hôtes SAN. Pour les hôtes SAN, les paramètres SnapInfo sont appliqués au niveau du volume. Pour les hôtes NAS, les paramètres SnapInfo sont appliqués au niveau du partage SMB.

Si vous avez ajouté l'adresse IP du système de stockage dans SnapDrive pour TPS Windows, les paramètres de stockage de SnapDrive pour Windows sont automatiquement renseignés lorsque vous exécutez l'assistant de configuration dans SnapManager pour Hyper-V. Si SnapDrive for Windows TPS n'est pas configuré, vous devez spécifier l'adresse IP du système de stockage dans l'onglet gérer les connexions de stockage de SnapManager for Hyper-V.

.Étapes
. Dans le volet de navigation, cliquez sur menu:protection[hosts].
. Sélectionnez l'hôte pour lequel vous souhaitez modifier le chemin d'accès au répertoire SnapInfo.
. Dans le volet *actions*, sélectionnez *Paramètres SnapInfo*.
+
La boîte de dialogue *SnapInfo Settings* s'ouvre.

. Sélectionnez le type de stockage parmi les options indiquées :
+
|===
| Option | Description 


 a| 
SAN
 a| 
Il s'agit du type de stockage par défaut.



 a| 
NAS
 a| 
Utilisez cette option pour les partages SMB.

|===
. Cliquez sur *Parcourir*.
+
La fenêtre Rechercher un dossier s'ouvre.

. Sélectionnez votre système de stockage (SAN) ou volume (NAS) SnapInfo et cliquez sur *OK*.
+
Les hôtes affichés sont des partages NAS correspondant aux systèmes de stockage qui ont été enregistrés à l'aide de `Manage Storage Connections` option au niveau de l'hôte. Si vous ne voyez pas les actions que vous recherchez, assurez-vous que `Manage Storage Connections` a été configuré correctement.

. Dans la fenêtre *SnapInfo Settings*, cliquez sur *OK*.

