---
permalink: task-restore-a-virtual-machine-from-a-backup-copy.html 
sidebar: sidebar 
keywords: snapmanager, hyper-v, restore, single, virtual, machine, vm, recover, lost, damage, data, backup, copy, restoring 
summary: 'Vous pouvez utiliser SnapManager pour Hyper-V, qui restaure à la fois une seule machine virtuelle afin de récupérer les données perdues ou endommagées à partir d"une copie de sauvegarde.' 
---
= Restaurer une machine virtuelle à partir d'une copie de sauvegarde
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser SnapManager pour Hyper-V, qui restaure à la fois une seule machine virtuelle afin de récupérer les données perdues ou endommagées à partir d'une copie de sauvegarde.

Vous devez disposer des informations suivantes :

* Nom de la sauvegarde
* Informations de configuration
* Informations sur le script


Lors d'une restauration sur un autre hôte, le type de CPU du PC physique sur lequel résidait la machine virtuelle d'origine doit être compatible avec l'ordinateur physique sur lequel vous souhaitez restaurer la machine virtuelle. Vous pouvez également utiliser Hyper-V Manager pour spécifier que la machine est autorisée à restaurer une machine avec un autre type de CPU.

Une fois le stockage en direct migré, vous ne pouvez plus effectuer la restauration à partir de la dernière sauvegarde.

Si vous lancez une opération de restauration d'une machine virtuelle Hyper-V et qu'une autre sauvegarde ou restauration de la même machine virtuelle est en cours, elle échoue.

.Étapes
. Dans le volet de navigation, cliquez sur *Recovery*.
. Sélectionnez la machine virtuelle à restaurer.
. Dans le volet sauvegardes, sélectionnez le nom de la copie de sauvegarde à restaurer et cliquez sur *Restaurer*.
+
L'assistant de restauration s'affiche.

. Suivez les étapes de l'assistant pour restaurer la copie de sauvegarde de la machine virtuelle.
+
La fermeture de l'assistant n'annule pas l'opération de restauration. SnapManager for Hyper-V valide la configuration de la machine virtuelle avant de lancer l'opération de restauration. En cas de modification de la configuration de la machine virtuelle, un avertissement s'affiche pour vous permettre de continuer ou d'annuler l'opération.



Vous pouvez afficher l'état de l'opération de restauration dans la fenêtre *gestion des travaux* ou vérifier les résultats de l'opération en visualisant le rapport dans la fenêtre *gestion des rapports*.

*Informations connexes*

xref:reference-restore-from-a-backup-after-failback.adoc[Effectuez une restauration à partir d'une sauvegarde après restauration]
